/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as PhonesIndexRouteImport } from './routes/phones.index'
import { Route as PhonesProductIdRouteImport } from './routes/phones.$productId'
import { Route as RepairIndexRouteImport } from './routes/repair.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonesIndexRoute = PhonesIndexRouteImport.update({
  id: '/phones/',
  path: '/phones/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonesProductIdRoute = PhonesProductIdRouteImport.update({
  id: '/phones/$productId',
  path: '/phones/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairIndexRoute = RepairIndexRouteImport.update({
  id: '/repair/',
  path: '/repair/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/phones/$productId': typeof PhonesProductIdRoute
  '/phones/': typeof PhonesIndexRoute
  '/repair/': typeof RepairIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/phones/$productId': typeof PhonesProductIdRoute
  '/phones': typeof PhonesIndexRoute
  '/repair': typeof RepairIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/phones/$productId': typeof PhonesProductIdRoute
  '/phones/': typeof PhonesIndexRoute
  '/repair/': typeof RepairIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/accessories' | '/phones/$productId' | '/phones/' | '/repair/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accessories' | '/phones/$productId' | '/phones' | '/repair'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/phones/$productId'
    | '/phones/'
    | '/repair/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  PhonesProductIdRoute: typeof PhonesProductIdRoute
  PhonesIndexRoute: typeof PhonesIndexRoute
  RepairIndexRoute: typeof RepairIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phones/': {
      id: '/phones/'
      path: '/phones'
      fullPath: '/phones/'
      preLoaderRoute: typeof PhonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phones/$productId': {
      id: '/phones/$productId'
      path: '/phones/$productId'
      fullPath: '/phones/$productId'
      preLoaderRoute: typeof PhonesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/': {
      id: '/repair/'
      path: '/repair'
      fullPath: '/repair/'
      preLoaderRoute: typeof RepairIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  PhonesProductIdRoute: PhonesProductIdRoute,
  PhonesIndexRoute: PhonesIndexRoute,
  RepairIndexRoute: RepairIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
